/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:22:41 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/


@class NSTimer, DOMNode, UIWebSelectionHandle, NSString, NSMutableArray, UIWebPDFView;

typedef struct CGPoint {
	double x;
	double y;
} CGPoint;

typedef struct CGSize {
	double width;
	double height;
} CGSize;

typedef struct __CFString* CFStringRef;

typedef struct __GSEvent* GSEventRef;

typedef struct __IOHIDEvent* IOHIDEventRef;

typedef struct __GSKeyboard* GSKeyboardRef;

typedef struct __CFMessagePort* CFMessagePortRef;

typedef struct UIEdgeInsets {
	double top;
	double left;
	double bottom;
	double right;
} UIEdgeInsets;

typedef struct CGVector {
	double dx;
	double dy;
} CGVector;

typedef struct CGImage* CGImageRef;

typedef struct _NSZone* NSZoneRef;

typedef struct CGPath* CGPathRef;

typedef struct CGPDFPage* CGPDFPageRef;

typedef struct {
	CGRect field1;
	CGRect field2;
	CGRect field3;
} SCD_Struct_UI13;

typedef struct __IOSurface* IOSurfaceRef;

typedef struct {
	double field1;
	double field2;
	double field3;
	double field4;
	double field5;
	double field6;
	double field7;
	double field8;
	double field9;
} SCD_Struct_UI15;

typedef struct {
	SCD_Struct_UI13 field1;
	SCD_Struct_UI13 field2;
	SCD_Struct_UI13 field3;
} SCD_Struct_UI16;

typedef struct CGColor* CGColorRef;

typedef struct NSDirectionalEdgeInsets {
	double top;
	double leading;
	double bottom;
	double trailing;
} NSDirectionalEdgeInsets;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct {
	long long field1;
	long long field2;
} SCD_Struct_UI21;

typedef struct {
	id field1;
	BOOL field2;
	int field3;
	BOOL field4;
	BOOL field5;
	BOOL field6;
	BOOL field7;
	BOOL field8;
	BOOL field9;
	BOOL field10;
	BOOL field11;
	BOOL field12;
	BOOL field13;
} SCD_Struct_UI22;

typedef struct CGContext* CGContextRef;

typedef struct CGAffineTransform {
	double a;
	double b;
	double c;
	double d;
	double tx;
	double ty;
} CGAffineTransform;

typedef struct NSRange {
	unsigned long long location;
	unsigned long long length;
} NSRange;

typedef struct UIOffset {
	double horizontal;
	double vertical;
} UIOffset;

typedef struct {
	unsigned long long field1;
	unsigned long long field2;
	BOOL field3;
	double field4;
	double field5;
	double field6;
} SCD_Struct_UI27;

typedef struct {
	double field1;
	double field2;
	double field3;
	double field4;
	double field5;
} SCD_Struct_UI28;

typedef struct CGShading* CGShadingRef;

typedef struct {
	long long width;
	long long height;
} SCD_Struct_UI30;

typedef struct {
	BOOL field1;
	BOOL field2;
	BOOL field3;
	BOOL field4;
	BOOL field5;
	double field6;
	int field7;
} SCD_Struct_UI31;

typedef struct {
	unsigned val[8];
} SCD_Struct_UI32;

typedef struct {
	CGPoint field1;
	CGPoint field2;
	double field3;
	double field4;
} SCD_Struct_UI33;

typedef struct {
	CGPoint field1;
	CGPoint field2;
	SCD_Struct_UI33 field3;
} SCD_Struct_UI34;

typedef struct {
	double field1;
	double field2;
	double field3;
} SCD_Struct_UI35;

typedef struct {
	SCD_Struct_UI35 field1;
	SCD_Struct_UI35 field2;
	SCD_Struct_UI35 field3;
	BOOL field4;
	BOOL field5;
	BOOL field6;
} SCD_Struct_UI36;

typedef struct {
	double field1;
	double field2;
	double field3;
	double field4;
	BOOL field5;
	BOOL field6;
	BOOL field7;
	BOOL field8;
} SCD_Struct_UI37;

typedef struct {
	BOOL field1[35];
	char field2[64];
	char field3[64];
	int field4;
	int field5;
	char field6[100];
	char field7[100];
	char field8[100];
	char field9[2][1024];
	unsigned field10;
	int field11;
	int field12;
	unsigned field13;
	int field14;
	unsigned field15;
	char field16[150];
	int field17;
	int field18;
	unsigned field19 : 1;
	unsigned field20 : 1;
	unsigned field21 : 1;
	char field22[256];
	unsigned field23 : 1;
	unsigned field24 : 1;
	unsigned field25 : 1;
	unsigned field26 : 1;
	unsigned field27 : 1;
	unsigned field28;
	unsigned field29 : 1;
	unsigned field30 : 1;
	unsigned field31 : 1;
	char field32[256];
	char field33[256];
	char field34[100];
	unsigned field35 : 1;
	unsigned field36 : 1;
	unsigned field37 : 1;
	double field38;
	unsigned field39 : 1;
} SCD_Struct_UI38;

typedef struct CATransform3D {
	double m11;
	double m12;
	double m13;
	double m14;
	double m21;
	double m22;
	double m23;
	double m24;
	double m31;
	double m32;
	double m33;
	double m34;
	double m41;
	double m42;
	double m43;
	double m44;
} CATransform3D;

typedef struct {
	id field1;
	id field2;
	id field3;
	id field4;
	id field5;
	CGSize field6;
} SCD_Struct_UI40;

typedef struct {
	id field1;
	double field2;
	double field3;
	SCD_Struct_UI40 field4;
	SCD_Struct_UI40 field5;
	SCD_Struct_UI40 field6;
	SCD_Struct_UI40 field7;
	BOOL field8;
} SCD_Struct_UI41;

typedef struct {
	unsigned idiom : 6;
	unsigned landscape : 1;
	unsigned split : 1;
	unsigned appearance : 8;
	unsigned rendering : 8;
	unsigned padding : 8;
} SCD_Struct_UI42;

typedef struct __CFRunLoopObserver* CFRunLoopObserverRef;

typedef struct __CFCharacterSet* CFCharacterSetRef;

typedef struct {
	CGPoint origin;
	CGPoint offset;
	int position;
	CGPoint desiredPoint;
	CGRect desiredBounds;
} SCD_Struct_UI45;

typedef struct {
	unsigned long long field1;
	id field2;
	unsigned long long field3;
	unsigned long long field4[5];
} SCD_Struct_UI46;

typedef struct {
	NSTimer* timer;
	CGPoint location;
	BOOL isBlocked;
	BOOL isCancelled;
	BOOL isOnWebThread;
	BOOL isDisplayingHighlight;
	BOOL attemptedClick;
	CGPoint lastPanTranslation;
	DOMNode* element;
	id delegate;
	id interactionSheet;
	 UIWebRotatingAlertController;
	BOOL allowsImageSheet;
	BOOL allowsDataDetectorsSheet;
	BOOL allowsLinkSheet;
	BOOL acceptsFirstResponder;
	double documentScale;
	id previewHintRects;
	 NSArray;
	id previewHintImage;
	 UIImage;
} SCD_Struct_UI47;

typedef struct UIWebViewportConfiguration {
	CGSize size;
	float initialScale;
	float minimumScale;
	float maximumScale;
	BOOL allowsUserScaling;
	BOOL allowsShrinkToFit;
	BOOL avoidsUnsafeArea;
} UIWebViewportConfiguration;

typedef struct UIWebTouchEvent {
	int type;
	double timestamp;
	CGPoint locationInScreenCoordinates;
	CGPoint locationInDocumentCoordinates;
	double scale;
	double rotation;
	BOOL inJavaScriptGesture;
	_UIWebTouchPoint touchPoints;
	unsigned touchPointCount;
	BOOL isPotentialTap;
} UIWebTouchEvent;

typedef struct {
	unsigned isKnown : 1;
	unsigned isSupported : 1;
	unsigned isInRange : 1;
} SCD_Struct_UI50;

typedef struct {
	float x;
	float y;
	float z;
} SCD_Struct_UI51;

typedef union GLKVector3 {
	SCD_Struct_UI51 field1;
	SCD_Struct_UI51 field2;
	SCD_Struct_UI51 field3;
	float v[3];
} GLKVector3;

typedef struct {
	GLKVector3 v;
	float s;
} SCD_Struct_UI53;

typedef struct {
	float x;
	float y;
	float z;
	float w;
} SCD_Struct_UI54;

typedef union GLKQuaternion {
	SCD_Struct_UI53 field1;
	SCD_Struct_UI54 field2;
	float q[4];
} GLKQuaternion;

typedef struct os_unfair_lock_s {
	unsigned _os_unfair_lock_opaque;
} os_unfair_lock_s;

typedef struct {
	double dampingRatio;
	double response;
	BOOL initialDampingRatioSpecified;
	BOOL initialResponseSpecified;
	double initialDampingRatio;
	double initialResponse;
	double dampingRatioSmoothing;
	double responseSmoothing;
	double targetSmoothing;
	double projectionDeceleration;
	double impulse;
} SCD_Struct_UI57;

typedef struct {
	id field1;
	unsigned long long field2;
} SCD_Struct_UI58;

typedef struct {
	unsigned long long direction;
	BOOL primaryActionIsDestructive;
	BOOL primaryActionCanBeTriggeredBySwipe;
	double openThreshold;
	double confirmationThreshold;
} SCD_Struct_UI59;

typedef struct {
	UIEdgeInsets field1;
	UIEdgeInsets field2;
	UIEdgeInsets field3;
	UIEdgeInsets field4;
	UIEdgeInsets field5;
} SCD_Struct_UI60;

typedef struct {
	BOOL itemIsEnabled[35];
	char timeString[64];
	char shortTimeString[64];
	int gsmSignalStrengthRaw;
	int gsmSignalStrengthBars;
	char serviceString[100];
	char serviceCrossfadeString[100];
	char serviceImages[2][100];
	char operatorDirectory[1024];
	unsigned serviceContentType;
	int wifiSignalStrengthRaw;
	int wifiSignalStrengthBars;
	unsigned dataNetworkType;
	int batteryCapacity;
	unsigned batteryState;
	char batteryDetailString[150];
	int bluetoothBatteryCapacity;
	int thermalColor;
	unsigned thermalSunlightMode : 1;
	unsigned slowActivity : 1;
	unsigned syncActivity : 1;
	char activityDisplayId[256];
	unsigned bluetoothConnected : 1;
	unsigned displayRawGSMSignal : 1;
	unsigned displayRawWifiSignal : 1;
	unsigned locationIconType : 1;
	unsigned quietModeInactive : 1;
	unsigned tetheringConnectionCount;
	unsigned batterySaverModeActive : 1;
	unsigned deviceIsRTL : 1;
	unsigned lock : 1;
	char breadcrumbTitle[256];
	char breadcrumbSecondaryTitle[256];
	char personName[100];
	unsigned electronicTollCollectionAvailable : 1;
	unsigned wifiLinkWarning : 1;
	unsigned wifiSearching : 1;
	double backgroundActivityDisplayStartDate;
	unsigned shouldShowEmergencyOnlyStatus : 1;
} SCD_Struct_UI61;

typedef struct {
	BOOL field1[35];
	unsigned field2 : 1;
	unsigned field3 : 1;
	unsigned field4 : 1;
	unsigned field5 : 1;
	unsigned field6 : 2;
	unsigned field7 : 1;
	unsigned field8 : 1;
	unsigned field9 : 1;
	unsigned field10 : 1;
	unsigned field11 : 1;
	unsigned field12 : 1;
	unsigned field13 : 1;
	unsigned field14 : 1;
	unsigned field15 : 1;
	unsigned field16 : 1;
	unsigned field17 : 1;
	unsigned field18 : 1;
	unsigned field19 : 1;
	unsigned field20 : 1;
	unsigned field21 : 1;
	unsigned field22;
	unsigned field23 : 1;
	unsigned field24 : 1;
	unsigned field25 : 1;
	unsigned field26 : 1;
	SCD_Struct_UI61 field27;
} SCD_Struct_UI62;

typedef struct __CFArray* CFArrayRef;

typedef struct __CFStringTokenizer* CFStringTokenizerRef;

typedef struct ui_archive* ui_archiveRef;

typedef struct ui_archive_entry* ui_archive_entryRef;

typedef struct {
	CGPoint point;
	double time;
} SCD_Struct_UI67;

typedef struct {
	UIWebSelectionHandle* scrollingHandle;
	double startTime;
	int direction;
	NSTimer* timer;
} SCD_Struct_UI68;

typedef struct {
	UIWebSelectionHandle* activeHandle;
	CGPoint handleCenterStart;
	double handleOffset;
} SCD_Struct_UI69;

typedef struct {
	BOOL flipPossible;
	BOOL rectsChanged;
	CGRect originalSelectionRect;
} SCD_Struct_UI70;

typedef struct {
	UIWebSelectionHandle* start;
	UIWebSelectionHandle* end;
	CGSize startingOffset;
	BOOL anchorAtStart;
	SCD_Struct_UI70 flipData;
} SCD_Struct_UI71;

typedef union {
	float floatValue;
	double doubleValue;
	unsigned long long integerValue;
	void bytesValue;
} SCD_Union_UI72;

typedef struct UINibArchiveTableInfo {
	unsigned count;
	unsigned offset;
} UINibArchiveTableInfo;

typedef struct UINibDecoderHeader {
	unsigned char type[10];
	unsigned formatVersion;
	unsigned coderVersion;
	UINibArchiveTableInfo objects;
	UINibArchiveTableInfo keys;
	UINibArchiveTableInfo values;
	UINibArchiveTableInfo classes;
} UINibDecoderHeader;

typedef struct UINibDecoderRecursiveState {
	long long objectID;
	long long nextGenericKey;
	unsigned nextValueSearchIndex;
	BOOL replaced;
} UINibDecoderRecursiveState;

typedef struct UIKeyToKeyIDCache {
	NSString* previousKey[64];
	void* previousKeyID[64];
	BOOL previousKeyExists[64];
	long long hashHits;
	long long hashHotMisses;
	long long hashColdMisses;
} UIKeyToKeyIDCache;

typedef struct UIKeyAndScopeToValueCache {
	unsigned previousScope;
	unsigned previousKey;
	UINibDecoderValue previousValue;
} UIKeyAndScopeToValueCache;

typedef struct {
	CGPoint field1;
	double field2;
} SCD_Struct_UI78;

typedef struct __CFBoolean* CFBooleanRef;

typedef struct {
	double amount;
	int unit;
} SCD_Struct_UI80;

typedef struct {
	SCD_Struct_UI80 field1[4];
} SCD_Struct_UI81;

typedef struct opaque_pthread_mutex_t {
	long long __sig;
	char __opaque[56];
} opaque_pthread_mutex_t;

typedef struct __DCSDictionary* DCSDictionaryRef;

typedef struct CGPDFDocument* CGPDFDocumentRef;

typedef struct {
	BOOL overrideItemIsEnabled[35];
	unsigned overrideTimeString : 1;
	unsigned overrideGsmSignalStrengthRaw : 1;
	unsigned overrideGsmSignalStrengthBars : 1;
	unsigned overrideServiceString : 1;
	unsigned overrideServiceImages : 2;
	unsigned overrideOperatorDirectory : 1;
	unsigned overrideServiceContentType : 1;
	unsigned overrideWifiSignalStrengthRaw : 1;
	unsigned overrideWifiSignalStrengthBars : 1;
	unsigned overrideDataNetworkType : 1;
	unsigned disallowsCellularDataNetworkTypes : 1;
	unsigned overrideBatteryCapacity : 1;
	unsigned overrideBatteryState : 1;
	unsigned overrideBatteryDetailString : 1;
	unsigned overrideBluetoothBatteryCapacity : 1;
	unsigned overrideThermalColor : 1;
	unsigned overrideSlowActivity : 1;
	unsigned overrideActivityDisplayId : 1;
	unsigned overrideBluetoothConnected : 1;
	unsigned overrideBreadcrumb : 1;
	unsigned overrideLock;
	unsigned overrideDisplayRawGSMSignal : 1;
	unsigned overrideDisplayRawWifiSignal : 1;
	unsigned overridePersonName : 1;
	unsigned overrideWifiLinkWarning : 1;
	SCD_Struct_UI61 values;
} SCD_Struct_UI85;

typedef struct __CFMachPort* CFMachPortRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct {
	BOOL animateContentRotation;
	BOOL preserveHeight;
	BOOL avoidFadingBottomOfContent;
	BOOL skipSnapshotOfEndState;
	BOOL preventAdditveAnimations;
	double contentStretchRightEdgeInset;
	int edgeClip;
} SCD_Struct_UI88;

typedef struct __CFSet* CFSetRef;

typedef struct UIPeripheralAnimationGeometry {
	CGPoint outPosition;
	CGPoint inPosition;
	CGRect bounds;
	CGAffineTransform transform;
	double targetFrameHeightDelta;
} UIPeripheralAnimationGeometry;

typedef struct {
	NSMutableArray* all;
	NSMutableArray* html;
	NSMutableArray* javascript;
	NSMutableArray* css;
	NSMutableArray* error;
	NSMutableArray* warning;
	NSMutableArray* tip;
	NSMutableArray* log;
} SCD_Struct_UI91;

typedef struct {
	UIWebPDFView* view;
	NSTimer* timer;
} SCD_Struct_UI92;

typedef struct __CFUserNotification* CFUserNotificationRef;

typedef struct {
	CGPoint field1;
	unsigned long long field2;
} SCD_Struct_UI94;

typedef struct objc_ivar* objc_ivarRef;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct PDFHistoryItem {
	BOOL restorePending;
	BOOL isInitialScale;
	double zoomScale;
	CGPoint contentOffset;
} PDFHistoryItem;

typedef union {
	SCD_Struct_UI42 styling;
	int intValue;
} SCD_Union_UI98;

typedef struct {
	double field1;
	long long field2;
	double field3;
	double field4;
	double field5;
	double field6;
} SCD_Struct_UI99;

typedef struct __CTFont* CTFontRef;

typedef struct CGPDFFont* CGPDFFontRef;

typedef struct {
	id field1;
	id field2;
} SCD_Struct_UI102;

typedef struct CGColorSpace* CGColorSpaceRef;

typedef struct {
	double rotationX;
	double rotationY;
	double rotationZ;
	double scaleX;
	double scaleY;
	double scaleZ;
	double translationX;
	double translationY;
	double translationZ;
} SCD_Struct_UI104;

typedef struct {
	unsigned field1 : 1;
} SCD_Struct_UI105;

typedef struct {
	BOOL field1;
	double field2;
	CGSize field3;
	CGSize field4;
	UIEdgeInsets field5;
	double field6;
	BOOL field7;
	BOOL field8;
	CGRect field9;
} SCD_Struct_UI106;

typedef struct {
	int commonRowHorizontalAlignment;
	int lastRowHorizontalAlignment;
	int rowVerticalAlignment;
} SCD_Struct_UI107;

typedef struct {
	CGPoint dampingRatioState;
	CGPoint responseState;
	double tension;
	double friction;
} SCD_Struct_UI108;

typedef struct {
	double targetValue;
	double tension;
	double friction;
} SCD_Struct_UI109;

typedef struct {
	SCD_Struct_UI109 dampingRatioParameters;
	SCD_Struct_UI109 responseParameters;
	SCD_Struct_UI109 targetParameters;
	BOOL dampingRatioSmoothingDisabled;
	BOOL responseSmoothingDisabled;
	BOOL targetSmoothingDisabled;
} SCD_Struct_UI110;

typedef struct CGGradient* CGGradientRef;

typedef struct {
	float x;
	float y;
} SCD_Struct_UI112;

typedef struct {
	SCD_Struct_UI112 position;
	 color;
} SCD_Struct_UI113;

typedef struct {
	SCD_Struct_UI109 field1;
	SCD_Struct_UI109 field2;
	SCD_Struct_UI109 field3;
	BOOL field4;
	BOOL field5;
	BOOL field6;
} SCD_Struct_UI114;

typedef struct __CTLine* CTLineRef;

typedef struct UIScreenBoundingPathBitmapInfo {
	unsigned long long width;
	unsigned long long height;
	unsigned long long skipRegionY;
	unsigned long long skipRegionHeight;
} UIScreenBoundingPathBitmapInfo;

typedef struct {
	unsigned field1 : 1;
	unsigned field2 : 1;
} SCD_Struct_UI117;

typedef struct {
	int phase;
	CGPoint position;
	double timestamp;
	double azimuth;
	double altitude;
	double pressure;
} SCD_Struct_UI118;

typedef struct {
	unsigned long long senderID;
	double controllerState[16];
	double normalizedLeftStickState[4];
	double normalizedRightStickState[4];
	double normalizedShoulderButtonState[4];
} SCD_Struct_UI119;

typedef struct {
	long long userInterfaceIdiom;
	double displayScale;
	long long displayGamut;
	long long touchLevel;
	unsigned long long interactionModel;
	unsigned long long primaryInteractionModel;
	long long horizontalSizeClass;
	long long verticalSizeClass;
	long long userInterfaceStyle;
	long long layoutDirection;
	long long forceTouchCapability;
	long long preferredContentSizeCategory;
	double displayCornerRadius;
} SCD_Struct_UI120;

