/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:22:15 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

@class UITextInteractionAssistant;


@protocol UITextInputPrivate <UITextInput,UITextInputTokenizer,UITextInputTraits_Private>
@property (nonatomic,readonly) UITextInteractionAssistant * interactionAssistant; 
@property (assign,nonatomic) long long selectionGranularity; 
@property (nonatomic,readonly) id<UITextInputSuggestionDelegate> textInputSuggestionDelegate; 
@property (assign,nonatomic) long long _textInputSource; 
@optional
-(BOOL)_shouldRepeatInsertText:(id)arg1;
-(double)_delayUntilRepeatInsertText:(id)arg1;
-(void)replaceRangeWithTextWithoutClosingTyping:(id)arg1 replacementText:(id)arg2;
-(void)insertDictationResult:(id)arg1 withCorrectionIdentifier:(id)arg2;
-(id)rangeWithTextAlternatives:(id*)arg1 atPosition:(id)arg2;
-(id)metadataDictionariesForDictationResults;
-(CGRect*)visibleRect;
-(id)textColorForCaretSelection;
-(long long)selectionGranularity;
-(void)setSelectionGranularity:(long long)arg1;
-(id)automaticallySelectedOverlay;
-(void)setBottomBufferHeight:(double)arg1;
-(BOOL)requiresKeyEvents;
-(void)handleKeyWebEvent:(id)arg1;
-(void)handleKeyWebEvent:(id)arg1 withCompletionHandler:(/*^block*/id)arg2;
-(id)selectionInteractionAssistant;
-(void)streamingDictationDidBegin;
-(void)streamingDictationDidEnd;
-(void)insertTextSuggestion:(id)arg1;
-(void)acceptedAutoFillWord:(id)arg1;
-(BOOL)isAutoFillMode;
-(id)fontForCaretSelection;
-(void)_insertAttributedTextWithoutClosingTyping:(id)arg1;
-(void)_willShowCorrections;
-(void)_didHideCorrections;
-(BOOL)_shouldSuppressSelectionCommands;
-(SEL)_sendCurrentLocationAction;
-(id<UITextInputSuggestionDelegate>)textInputSuggestionDelegate;
-(long long)_textInputSource;
-(void)set_textInputSource:(long long)arg1;

@required
-(UITextInteractionAssistant *)interactionAssistant;
-(void)selectAll;
-(id)textInputTraits;
-(NSRange*)selectionRange;
-(BOOL)hasSelection;
-(BOOL)hasContent;

@end

