import socket
import time

TOAST_TYPE_SUCCESS = 4
TOAST_TYPE_NORMAL = 3
TOAST_TYPE_WARNING = 2
TOAST_TYPE_ERROR = 1

def showToast(s, type, content, duration):
    s.send(("22" + str(type) + ";;" + str(content) + ";;" + str(duration) + "\r\n").encode())
    print(s.recv(1024))



s = socket.socket()
s.connect(("127.0.0.1", 6000))  # connect to the tweak
time.sleep(0.1)  # please sleep after connection.

s.send("244;;3".encode())

showToast(s, TOAST_TYPE_NORMAL, "Opening Notes...", 2)
time.sleep(2)

showToast(s, TOAST_TYPE_NORMAL, "Please select an input field! 3...", 1)
time.sleep(1)

showToast(s, TOAST_TYPE_NORMAL, "Please select an input field! 2...", 1)
time.sleep(1)

showToast(s, TOAST_TYPE_NORMAL, "Please select an input field! 1...", 1)
time.sleep(1)

showToast(s, TOAST_TYPE_WARNING, "Inserting text...", 1.5)
s.send("241;;This text is generated by zxtouch!\r\n".encode())
time.sleep(1.5)

showToast(s, TOAST_TYPE_WARNING, "Hiding the keyboard...", 1.5)
s.send("242;;1\r\n".encode())
time.sleep(1.5)

showToast(s, TOAST_TYPE_WARNING, "Move cursor to the left by 3 position", 1.5)
s.send("243;;-3\r\n".encode())
time.sleep(1.5)

showToast(s, TOAST_TYPE_WARNING, "Delete 3 characters...", 1.5)
s.send("244;;3\r\n".encode())
print(s.recv(1024)) # Remember to recv after sending. Otherwise, for some reason, it won't work...


s.close() 
